### ISSUE TITLE
This site can't be reached after using npm start

### ISSUE THREAD

**Issue by iLightFPS** [rhysmorgan134/react-js-carplay#5]
I don't know if i'm dumb or just stupid dumb. But i can't get this to show in the browser. 

I've cloned the repo, removed lock.json file and then npm install. 

After that i just did npm start.  

It displays this after

```
asset index.js 498 KiB [emitted] [minimized] [big] (name: main) 1 related asset
orphan modules 2.15 MiB [orphan] 963 modules
runtime modules 1.17 KiB 6 modules
built modules 1.22 MiB [built]
  modules by path ./node_modules/ 436 KiB 60 modules
  modules by path ./src/ 812 KiB
    ./src/index.js + 240 modules 811 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js!./src/Carplay.css 1.26 KiB [built] [code generated]
  external "react" 42 bytes [built] [code generated]
  util (ignored) 15 bytes [built] [code generated]
  util (ignored) 15 bytes [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  index.js (498 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (498 KiB)
      index.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.88.2 compiled with 3 warnings in 7280 ms
```

Brower doesn't open nor do i get anything if i type in localhost or ip in the browser.

**Comment by rhysmorgan134** [comment]
This is just a reusable react component, the one you are after is https://github.com/rhysmorgan134/react-carplay

After install, npm start, then next window npm start-electron

**Comment by iLightFPS** [comment]
Getting this after doing the react-carplay instead 

npm start

> carplay@3.0.2 start
> export BROWSER=none && react-app-rewired start

'export' is not recognized as an internal or external command,
operable program or batch file.

**Comment by iLightFPS** [comment]
I got it. i changed export to set and it started the enviroment. Getting some warning messages but will open a ticket at react-carplay if i don't fix them
